import React from 'react';

const Footer = () => {
    return (
        <footer className="border-t py-6 md:w-[60%] w-[90%] mx-auto text-sm text-gray-600 mt-10">
            <div className="flex flex-col md:flex-row justify-between gap-6">
                {/* Informazioni */}
                <div className="flex-1">
                    <h2 className="font-bold mb-2 text-gray-900 text-xl">Papa's Company</h2>
                    <p className="text-lg">
                        Free to use for learning and personal use.<br />
                        <span className="text-red-600 font-medium">Do not copy, resell, or redistribute content generated by this platform.</span>

                    </p>
                    <p  className="text-lg">Warning, AI may generate incorrect information. </p>
                </div>

                {/* Contatti */}
                <div className="flex-1">
                    <h4 className="font-semibold text-gray-800 mb-2">Contact</h4>
                    <ul className="space-y-1 text-lg">
                        <li><a href="https://linkedin.com" target="_blank" className="hover:underline text-green-700">LinkedIn</a></li>
                        <li><a href="https://github.com/paparesta-007" target="_blank" className="hover:underline text-green-700">GitHub</a></li>
                        <li><a href="mailto:t.paparesta@gmail.com" className="hover:underline text-green-700">t.paparesta@gmail.com</a></li>
                        <li><a href="tel:+1234567890" className="hover:underline text-green-700">+39 347 303 8049</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    );
};

export default Footer;
